### PR TITLE
fix: StringT: re-support other string encodings

### LINKED ISSUE #61: Version 3.0.1 causes `react-pdf` `renderToStream` to never return
Hi!

I unfortunately do not have an easy direct reproduction, but the 3.0.1 version is causing issues with `react-pdf`. It's `renderToStream` function no longer completes after the update.

You can find the initial bug report here: https://github.com/diegomura/react-pdf/issues/2675

It was probably introduced by https://github.com/foliojs/restructure/pull/52, but I am unsure how to figure out what is happening here.

### PR DESCRIPTION
**Pull request by srl295**
- Fixes https://github.com/foliojs/restructure/issues/60
- Fixes https://github.com/foliojs/fontkit/issues/331 - allows fontkit's unit tests to pass
- Probably fixes #61 

- add a test for 'x-mac-roman'
- add two utf-16 alias names
- if an encoding is otherwise unknown, assume 1-byte length
(this matches prior behavior)

History: #59 enabled support for 2-byte utf encodings, which were previously broken. So #59+#62 presents no regression for any other encodings.

### CODE REVIEW

**Comment by srl295** [comment]
I'm still investigating what is happening here.

File: src/String.js [hunk 1]
```diff
@@ -95,9 +95,12 @@ function encodingWidth(encoding) {
   switch(encoding) {
     case 'ascii':
     case 'utf8': // utf8 is a byte-based encoding for zero-term string
+    case 'x-mac-roman':
       return 1;
     case 'utf16le':
     case 'utf16-le':
+    case 'utf-16be':
+    case 'utf-16le':
```
Comment (srl295) [inline src/String.js:103]: these should probably be here

File: src/String.js [hunk 2]
```diff
@@ -95,9 +95,12 @@ function encodingWidth(encoding) {
   switch(encoding) {
     case 'ascii':
     case 'utf8': // utf8 is a byte-based encoding for zero-term string
+    case 'x-mac-roman':
```
Comment (srl295) [inline src/String.js:98]: fontkit uses a few others as well. Need fallback handling? Or is it an API usage issue?

Comment (renchap) [reply src/String.js:98]: As this issue can cause an infinite loop, I would expect either:
- a fallback
- an explicit exception if the value is not handled and will possibly cause an infinite loop

Comment (srl295) [reply src/String.js:98]: I don't think there's an infinite loop here. Perhaps the calling code or its callers have a loop?

Comment (srl295) [reply src/String.js]: @renchap for now, I have it assume 1-byte, which matches previous behavior

**Comment by srl295** [comment]
FYI @blikblum @devongovett

**Comment by blikblum** [comment]
This seems to fix the fontkit issue. The ideal would be a reproduction for the react-pdf issue, but i think is good to go

**Review by mcdurdin — APPROVED** [review]
> As this issue can cause an infinite loop, I would expect either:
> 
> * a fallback
> * an explicit exception if the value is not handled and will possibly cause an infinite loop

I did a careful analysis of the while loop. I could not find any possibility of an infinite loop. It was, in my understanding, the exception in `encodingLength()` that was _causing_ the hang, my guess because it was being handled in another layer and causing the stream reader to never emit end-of-stream -- which I think could be considered a separate bug in that layer. However I have not yet had time to analyse at that level. I will have a go when I am online again (travelling all this week with limited online availability).

The changes look good to me, thank you @srl295 for jumping on this while I was incommunicado. Apologies to all for the regression.

File: src/String.js [hunk 3]
```diff
@@ -98,12 +98,16 @@ function encodingWidth(encoding) {
...
+    case 'utf-16le':
     case 'utf16be':
     case 'utf16-be':
     case 'ucs2':
       return 2;
     default:
-      throw new Error('Unknown encoding ' + encoding);
+      //TODO: assume all other encodings are 1-byters
+      //throw new Error('Unknown encoding ' + encoding);
+      return 1;
```
[the remark this answers is not in the document]
Comment (srl295) [reply src/String.js:110]: ^ the throw may have only been on encode() or bytelength() before, which is a more restricted set of encodings.

[the remark this answers is not in the document]
Comment (srl295) [reply src/String.js:110]: `x-mac-roman` is actually a _known_ encoding, as well, it's handled by the underlying encoder.  So one thing that could be done is to expand the set of encodings here to be exhaustive.

[the remark this answers is not in the document]
Comment (blikblum) [reply src/String.js:110]: AFAIK this PR brings back the previous behavior which is good enough. Lets do the minimal changes, unless there's a reproduction with an actual bug

**Comment by srl295** [comment]
@blikblum thanks.  and I assume this will get a patch release also?  By the way 3.0.1 is absent from https://github.com/foliojs/restructure/releases

**Comment by blikblum** [comment]
I have write access to github but don't have npm publish permission. @devongovett can publish a new version

**Comment by IvanUkhov** [comment]
Thank you for fixing! Looking forward to a release.

**Comment by karlhorky** [comment]
@devongovett friendly ping, would it be possible to get a new release, eg. [`restructure@3.0.2`](https://github.com/foliojs/restructure/releases/tag/v3.0.2)?

This is causing some confusing breakage (indefinite hanging with custom fonts, but only some of them) in `@react-pdf/renderer` and `fontkit`:

- https://github.com/diegomura/react-pdf/issues/2675
- https://github.com/foliojs/fontkit/issues/331

**Comment by devongovett** [comment]
Done!
